#!/system/xbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.googymax4/.googymax4.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.googymax4/battery.profile /data/.googymax4/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.googymax4/balanced.profile /data/.googymax4/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.googymax4/performance.profile /data/.googymax4/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
