#!/system/xbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  
    stop mpdecision
    echo "1" > /sys/devices/system/cpu/cpu0/online
    echo "1" > /sys/devices/system/cpu/cpu1/online
    echo "1" > /sys/devices/system/cpu/cpu2/online
    echo "1" > /sys/devices/system/cpu/cpu3/online
    echo "$cpu_governor" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    echo "$cpu_governor" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
    echo "$cpu_governor" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
    echo "$cpu_governor" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
    start mpdecision

echo "CPU Governor applied : $cpu_governor"

fi
fi
